services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8000:8000"

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - db
    environment:
      RABBITMQ_HOST: rabbitmq
      POSTGRES_HOST: db
      POSTGRES_DB: weather
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
    ports:
      - "8001:8001"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - rabbitmq
      - db
      - rabbitmq-exporter
      - postgres-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: rabbitmq-exporter
    restart: always
    environment:
      RABBIT_URL: http://guest:guest@rabbitmq:15672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    ports:
      - "9419:9419"
    depends_on:
      - rabbitmq

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://weatheruser:weatherpass@db:5432/weather?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db

volumes:
  rabbitmq-data:
    driver: local
  postgres-data:
    driver: local
  grafana-data:
    driver: local